plugins {
    id "net.fabricmc.fabric-loom-remap" version "1.17-SNAPSHOT"
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:2025.12.20@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    compileOnly(project(":client"))

    modImplementation "maven.modrinth:combatradar:1.7.9-1.21.11"
    modImplementation "maven.modrinth:voxelmap-updated:1.21.11-1.16.6"
    modImplementation "maven.modrinth:xaeros-minimap:fabric-1.21.11-26.2.0"
    modImplementation "maven.modrinth:journeymap:1.21.11-6.0.0+fabric"
    modImplementation "maven.modrinth:tF3LNnBc:f5N3TG1b"
    modCompileOnlyApi "info.journeymap:journeymap-api-fabric:2.0.0-1.21.1"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

java {
    withSourcesJar()
}